export const site = {
  siteName:      "ProLife",
  siteURL:       "prolife-org-ua.netlify.app",
  siteEmail1:    "prolife.org.ua@gmail.com",
  siteEmail2:    "",
  siteEmail3:    "",
  siteTel1:      "+38 097 787 15 10",
  siteTel2:      "",
  siteTel3:      "",
  siteGeo:       "https://goo.gl/maps/cdRAzZg1EM8CMwEX6",
  siteFacebook:  "facebook.com/prolife-org-ua",
  siteTelegram:  "t.me/prolife-org-ua",
  siteAddr1:     "вул. Францисканська, 4,",
  siteAddr2:     "Кам'янець-Подільський,",
  siteAddr3:     "32301, Україна",

  artSlug:       "articles/the-cosmos-awaits",
  artTitle:      "The Cosmos awaits",
  artBanner:     "https://images.ctfassets.net/gioiz80bo502/7LcF0XIMP6LZ3OdMoazA00/220b8f3f5a192676ca8b8364be4b449f/federico-beccari-L8126OwlroY-1920x1080.jpg",
  artAuthor:     "<p>Dr. <strong>Leonard Hofstadter</strong></p><p>senior experimental physicist at the California Institute of Technology</p><p><a href=\"https://bigbangtheory.fandom.com/wiki/Leonard_Hofstadter\">www.wiki.info/Leonard_Hofstadter</a></p>",
};
